### ISSUE TITLE
Problema nos cards quando a descrição do repositório é grande demais.

### ISSUE THREAD

**Issue by NKKFu** [LauraBeatris/codio#3]
Não prejudica o funcionamento do sistema, é só um pequeno bug visual que incomoda.

**Screenshot:**

![cool](https://i.ibb.co/n0zvDWj/cool.png)

_(Ps: É o meu primeiro Issue criado 😬)_

**Comment by LauraBeatris** [comment]
Hey @NKKFu, is it your first issue? That's pretty cool hahaha what an honor 

Thanks for contributing <3 

Issue fixed in fc3d841d8bf3954f5a51e672693ada29e9b1fdb7
