### ISSUE TITLE
Redirect tecnologies in README

### ISSUE THREAD

**Issue by akinncar** [LauraBeatris/codio#5]
In [FAQ](https://github.com/LauraBeatris/codio#postbox-faq) section on README, the **React** link is redirected to [NodeJS page](https://nodejs.org/en/).

**Expected:** Be redirected to [ReactJS page](https://reactjs.org/).

**Comment by LauraBeatris** [comment]
Hey @akinncar 

Thanks for you contribution ❤️ 

Just fixed it in 17b8f623f1a0aab7c0de9309aaea075b42cdaef8
